"""
Trading Signals Page
View and manage trading signals from various strategies
"""

from nicegui import ui, run
from ..common import Components
import sys
from pathlib import Path
import asyncio
import requests

sys.path.append(str(Path(__file__).parent.parent.parent))

API_BASE = "http://localhost:9000/api"


def render_page(state):
    Components.section_header(
        "Trading Signals",
        "View signals generated by trading strategies",
        "track_changes",
    )

    content_container = ui.column().classes("w-full mt-6 gap-6")

    # Strategy Filter
    with Components.card():
        with ui.row().classes("w-full gap-4 items-end"):
            strategy_select = ui.select(
                label="Filter by Strategy",
                options=["All Strategies"],
                value="All Strategies",
            ).classes("flex-1")

            ui.button("Refresh", on_click=lambda: load_signals(), icon="refresh").props(
                "flat"
            )

    signals_container = ui.column().classes("w-full gap-4")

    async def load_signals():
        signals_container.clear()

        with signals_container:
            ui.spinner("dots", size="lg").classes("mx-auto text-indigo-500")

        try:
            # Determine endpoint based on filter
            if strategy_select.value == "All Strategies" or not strategy_select.value:
                endpoint = f"{API_BASE}/signals"
            else:
                endpoint = f"{API_BASE}/signals/{strategy_select.value}"

            response = await run.io_bound(requests.get, endpoint)
            signals_container.clear()

            if response.status_code == 200:
                signals = response.json()

                with signals_container:
                    if not signals:
                        with Components.card():
                            ui.label("No signals available").classes(
                                "text-slate-400 italic"
                            )
                    else:
                        render_signals_table(signals)
            else:
                with signals_container:
                    with Components.card():
                        ui.label("Error loading signals").classes("text-red-400")
        except Exception as e:
            signals_container.clear()
            with signals_container:
                with Components.card():
                    ui.label(f"Error: {str(e)}").classes("text-red-400")

    def render_signals_table(signals):
        """Render signals in a table"""
        with Components.card():
            ui.label(f"Signals ({len(signals)})").classes("text-xl font-bold mb-4")

            columns = [
                {
                    "name": "timestamp",
                    "label": "Time",
                    "field": "timestamp",
                    "align": "left",
                },
                {
                    "name": "strategy",
                    "label": "Strategy",
                    "field": "strategy",
                    "align": "left",
                },
                {
                    "name": "symbol",
                    "label": "Symbol",
                    "field": "symbol",
                    "align": "left",
                },
                {
                    "name": "signal_type",
                    "label": "Signal",
                    "field": "signal_type",
                    "align": "left",
                },
                {
                    "name": "price",
                    "label": "Price",
                    "field": "price",
                    "align": "right",
                },
                {
                    "name": "confidence",
                    "label": "Confidence",
                    "field": "confidence",
                    "align": "right",
                },
                {
                    "name": "status",
                    "label": "Status",
                    "field": "status",
                    "align": "left",
                },
            ]

            table = ui.table(columns=columns, rows=signals, row_key="id")

            # Custom slot for signal type with color coding
            table.add_slot(
                "body-cell-signal_type",
                """
                <q-td :props="props">
                    <q-badge :color="props.row.signal_type === 'BUY' ? 'positive' : 'negative'">
                        {{ props.row.signal_type }}
                    </q-badge>
                </q-td>
            """,
            )

            # Custom slot for status
            table.add_slot(
                "body-cell-status",
                """
                <q-td :props="props">
                    <q-badge 
                        :color="props.row.status === 'active' ? 'primary' : 
                               props.row.status === 'executed' ? 'positive' : 'grey'">
                        {{ props.row.status }}
                    </q-badge>
                </q-td>
            """,
            )

    # Initial load
    ui.timer(0.1, load_signals, once=True)

    # NSE Instruments Section
    with Components.card().classes("mt-6"):
        ui.label("NSE Equity Instruments").classes("text-xl font-bold mb-4")

        search_input = ui.input(
            label="Search Instruments", placeholder="e.g., RELIANCE"
        ).classes("w-full mb-4")

        instruments_container = ui.column().classes("w-full")

        async def search_instruments():
            if not search_input.value or len(search_input.value) < 2:
                ui.notify("Please enter at least 2 characters", type="warning")
                return

            instruments_container.clear()
            with instruments_container:
                ui.spinner("dots", size="lg").classes("mx-auto text-indigo-500")

            try:
                response = await run.io_bound(
                    requests.get,
                    f"{API_BASE}/instruments/nse-eq",
                    params={"search": search_input.value},
                )

                instruments_container.clear()

                if response.status_code == 200:
                    instruments = response.json()

                    with instruments_container:
                        if not instruments:
                            ui.label("No instruments found").classes(
                                "text-slate-400 italic"
                            )
                        else:
                            columns = [
                                {
                                    "name": "symbol",
                                    "label": "Symbol",
                                    "field": "symbol",
                                    "align": "left",
                                },
                                {
                                    "name": "name",
                                    "label": "Name",
                                    "field": "name",
                                    "align": "left",
                                },
                                {
                                    "name": "sector",
                                    "label": "Sector",
                                    "field": "sector",
                                    "align": "left",
                                },
                                {
                                    "name": "market_cap",
                                    "label": "Market Cap",
                                    "field": "market_cap",
                                    "align": "right",
                                },
                            ]

                            ui.table(
                                columns=columns,
                                rows=instruments[:50],
                                row_key="symbol",
                            ).classes("w-full")

                            if len(instruments) > 50:
                                ui.label(
                                    f"Showing 50 of {len(instruments)} results"
                                ).classes("text-sm text-slate-400 mt-2")
                else:
                    with instruments_container:
                        ui.label("Error searching instruments").classes("text-red-400")
            except Exception as e:
                instruments_container.clear()
                with instruments_container:
                    ui.label(f"Error: {str(e)}").classes("text-red-400")

        search_input.on("keydown.enter", search_instruments)
        ui.button("Search", on_click=search_instruments, icon="search").props(
            "color=primary"
        )
